language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: Die+iO0EhD6Bi/GRtugpBS9HzDZUf20lfT3xrnbfrJyuEwIIBoxW4mJQBbVel7R02Zoo7lEKnfOUfcbBWG7n3vR10ORQZeCyAghkYwBifAEvpd0agipD2p7Xb7U8CF93RNs9+hrNUY21W6noi/4yyHwxW/SnI0tI9PUPX3rKd/N+WnPSm3ZSVKxeaaIxIhJyAnw4TbYnkmGi9OofcAk1Q3XIKRNrtizjQU+qvznqolmYgRPytc2cKIW+7CX8WSNzmtFTbmYaSSC6TeN/cWvIUvrVLhyVzu/djwvnS2hjoGLiCMFQJTqFNaHOkiVX+FvTn8rzV7Fo6Vsj295HRMPf3AE0cCgBa8opwg0bdMhfkrOkSviI/cbH58XslIBIIntirzh7kPxy2P1Dx5n9GbA0xjNO6vR0dmv487WBrYxRbrSdCHGZNTQ8305vSQKM1hYeXf/7bN1NkjzgrKCHgJaNIGW/Vr8jJziJMhMnS3pb2F8zdcMmw2xNg48+ntSIaxKwM0F052xuidk5EyNMNXugUK1qTfEY9/Q09VCnyQZkqaIg8oqaB27ny+9+Bhoe0hH48h3/ON526SBwaKHsqOTWOUOOTcNqa893sHuDfuaox4PGWON9Bqa5gJ8ir0jM8wrGZrFegalWJmM99+38U+t7HhS6mrOEK4e7C3X8b2xlurQ=
