language: java
jdk:
- openjdk8
script:
  - echo "skipping tests"
deploy:
  provider: heroku
  app: horse-battery-67
  api_key:
    secure: QzST1POrd9pVItA8n+FdaD/p0m/bFQlQAg6M6v/qCHdj+y8/lVLPcqWuSmLmxU/e+BGwLayg6jAg8eEMX906zSIoMq124aIB8CBYhlK74EfhFTQhwT2pjdQ5wi54LdjpjpUeeN0CkCHU2IQOoZYXrbASBOt1BwfH/pBaL1uZJ0UAR6SH/tjPiRSjsTb6QjWbTjkL2SZVDpneJ0kjqpGGhJnl7JfeiV9DibG1Mqp+S+ovInwlddx+4OE5uIqIUILQeAPaCgsrkkTTq6+oCNxlo0byaulNEyaZJgfk1SBcw9QyBWVzIBRdsET2PI84FwBdkLO5qwKHI4tINjJA4VuailTG6xCX3xfnptR+3hAIYFnMMH7LJB92VixDiLxy9zpbiEzsvDzSNPwGgUm4LekE/jvZEuN+DJh7yxaS2N//+o3j3KC6Cg49xlDvGsjatfCB7iKYaFL9NkVhZ/fDeC2aDQ+ePe7Q68NXb/5ISVL2A4EWPJGK8kTjkNc0wy6KSCW11cLON9syLkFQDqNJTrI3ToLlx4N4yZh0Vu1uGkzp4Eh1QkelxffeNrtJJur5FdJ/TLGWcr8S0pM1hCZRwsyJEjO/uY/iC+aUIPVGPmFJJkgRUoscarXviaLbrw26l3YXORbQ8aOk1ucgkZ1VMFWG5rXA7WKGvH84eCkAUbRlCDs=
